config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
    get '/articles/search_news' => 'articles#search_news'
    get '/authors/search_friends' => 'authors#search_friends'
	get 'help' => 'static_pages#help'
	get 'about' => 'static_pages#about'
	get 'contact' => 'static_pages#contact'
	get 'signup' => 'authors#new'
	get 'login' => 'sessions#new'
	get'recommend'=>'articles#recommend'
	get'all'=>'articles#all'
	post 'login' => 'sessions#create'
	delete 'logout' => 'sessions#destroy'
	resources :authors do
		 resources :comments
	end
  get 'static_pages/home'

  get 'static_pages/help'

  get 'comments/create'

  get 'comments/destroy'
resources :articles do  
    resources :comments 
    resources :authors 
  end  
resources :comments do  
    resources :authors 
end
	get ':controller(/:action(/:info))'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
<div class="w-full" style="background-color: #333333; height: auto;">
  <div class="container" style="text-align: center;">
    <br>
    <div style="margin: 0 auto;">
        <p class="pull-left col-lg-3 col-md-3 col-sm-4 col-xs-4"><a target="_blank" href="http://www.chinanews.com/" style="color: #ccc;"> 中国新闻网</a></p>
        <p class="pull-left col-lg-3 col-md-3 col-sm-4 col-xs-4"><a target="_blank" href="www.baidu.com"style="color: #ccc;"> 百度一下</a></p>
        <p class="pull-left col-lg-3 col-md-3 col-sm-4 col-xs-4"><a target="_blank" href="http://www.ucas.ac.cn/" style="color: #ccc;">中国科学院大学</a></p>
        <p class="pull-left col-lg-3 col-md-3 col-sm-4 col-xs-4"><a target="_blank" href="https://github.com/moonsea/ucas_today" style="color: #ccc;">Github</a></p>
    </div>
    <p>版权所有@天猫创作团队</p>
    <p>2016年1月1日</p>
  </div>
</div>
</footer>

app/views/layouts/_friends.html.erb
<%  if @authors!=nil  %> 
<%  @authors=@authors.sort{|x,y| y.id<=>x.id}  %>
    <div class="container">
      <% @authors.each do |author| %>
          <div class="col-lg-3 col-md-3 col-sm-4 col-xs-6" style="margin-bottom: 20px; cursor: pointer;">
            <img src="http://placehold.it/80x80" class="img-responsive img-rounded pull-left"/>
            <div class="pull-left" style="margin-left:1.5em;">
              <%= link_to author.name, author,style: 'line-height:45px;' %>
              <br>
              <%= author.created_at.to_s.first(10)%>
            </div>
          </div>
      <% end %>
    </div>

<%  else   %> 
不好啦 您寻找的小伙伴被外星人抓走啦
<% end   %> 

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
<div class="container">

<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false" onClick="showMenu();">
  <span class="sr-only">Toggle navigation</span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</button>
<a href="#">
  <%=image_tag "logo.png",class: "img-responsive logo hidden-lg hidden-md hidden-sm" %>
</a>
</div>

<div class="collapse navbar-collapse" id="navTop">
    <ul class="nav navbar-nav navbar-left">
      <li class="navbar-header hidden-xs">
        <%=image_tag "logo.png",class: "img-responsive logo" %>
      </li>
      <li>
        <h3 style="margin: 0; line-height: 50px; margin-left: 14px;">TODAY</h3>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li style="margin-right: 2em;">
        <form action="/articles/search_news" role="form" id="f">
          <table width="300" height="50" border="0" cellpadding="0" cellspacing="0" align="center">
            <tr>
              <td width="250" align="left" valign="middle" height="50">
                <input type="text" class="form-control" name="keywords" style="margin-top:0; margin-bottom: 0; border-right:none; border-radius: 5px 0 0 5px;">
              </td>
              <td width="50" align="left" valign="middle" height="50">
            <span class="btn btn-default" style="padding-left: 5px; border-radius: 0 5px 5px 0;" onclick="javascript:$('#f').submit();">
              <i class="glyphicon glyphicon-search"></i>
              搜索
            </span>
              </td>
            </tr>
          </table>
        </form>
      </li>
    <li><%= link_to "首页", root_path %></li>
    <% if logged_in? %>
    <li><%= link_to "找些小伙伴吧", authors_path %></li>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        我的账户 <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
        <li style="padding-left: 1em;"><i class="glyphicon glyphicon-user"></i><%= link_to current_author.name, current_author, style: 'display: inline-block' %></li>
        <li style="padding-left: 1em;"><i class="glyphicon glyphicon-pencil"></i><%= link_to "我要发文章", new_article_path, style: 'display: inline-block' %></li>
        <li style="padding-left: 1em;"><i class="glyphicon glyphicon-wrench"></i><%= link_to "设置", edit_author_path(current_author), style: 'display: inline-block'  %></li>
        <li class="divider"></li>
        <li style="padding-left: 1em;">
        <i class="glyphicon glyphicon-log-out"></i>
        <%= link_to "注销", logout_path, method: "delete", style: 'display: inline-block'   %>
        </li>
        </ul>
    </li>
    <% else %>
      <li><%= link_to "登录", login_path %></li>
      <li><%= link_to "注册", 'signup' %></li>
    <% end %>
    <li><%= link_to "帮助", help_path %></li>

</ul>
</div>
</div>
  <script>
      var isHide = true;
      function showMenu()
      {
          if(isHide)
          {
              $("#navTop").show(200);
          }
          else
          {
              $("#navTop").hide(200);
          }
          isHide = !isHide;
      }
  </script>
</header>

app/views/layouts/_index.html.erb
<%  if @articles!=nil  %> 
    <%  @articles=@articles.sort{|x,y| y.id<=>x.id}  %>
    <div class="container">
      <div class="col-lg-9 col-mg-9 col-sm-12 col-xs-12">
        <ul>
          <% @articles.each do |article| %>
              <li style="padding: 1em; height: auto; overflow: auto;">
                <table width="100%" height="auto" align="left">
                  <tr>
                    <td width="20%" height="120" align="left" valign="middle"class="hidden-xs hidden-sm">
                      <img src="http://placehold.it/120x120" />
                    </td>
                    <td width="80%" height="120" align="left" valign="top">
                      <h5 class="pull-left"><%= link_to article.title, article%></h5>
                      <label class="label label-info pull-right">
                        <%= link_to article.info, "/articles/info/#{article.info}", class: 'blocka'%>
                      </label>
                      <div class="clearfix"></div>
                      <p>
                        <%= article.text.first(150) %>...
                      </p>
                      <div class="pull-right">
                        <p><%=  article.author.name %>&nbsp;&nbsp;&nbsp;&nbsp;<%=  article.created_at %></p>
                      </div>
                    </td>
                  </tr>
                </table>
              </li>
          <% end %>
        </ul>
      </div>
      <div class="col-lg-3 col-mg-3 col-sm-12 col-xs-12">
        <ul class="list-group" style="list-style: none" id="new_man">
          <li><h4><i class="glyphicon glyphicon-fire">&nbsp;</i>欢迎新来的姑娘和汉子们</h4></li>
          <br>
          <% @users.each do |user|%>
              <li style="height: auto; overflow: auto; margin-bottom: 10px;">
                <img src="http://placehold.it/60x60" class="img-responsive img-circle pull-left" style="margin-top: 5px;"/>
                <%=link_to user.name,user,class:'pull-left',style:'display:block; line-height:60px; margin-left:1em;' %>
                <p class="pull-right" style="line-height: 60px;"><%= user.created_at.to_s.first(10)%></p>
              </li>
          <% end %>
          <br/>
          <li><h4><i class="glyphicon glyphicon-leaf">&nbsp;</i>瞻仰一下咱的大腕儿们</h4></li>
          <br>
          <% @users.each do |user|%>
              <li style="height: auto; overflow: auto; margin-bottom: 10px;">
                <img src="http://placehold.it/60x60" class="img-responsive img-circle pull-left" style="margin-top: 5px;"/>
                <%=link_to user.name,user,class:'pull-left',style:'display:block; line-height:60px; margin-left:1em;' %>
                <p class="pull-right" style="line-height: 60px;"><%= user.created_at.to_s.first(10)%></p>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
<%  else %>
    <div class="login">
      抱歉，暂时没有您需要的信息
    </div>
<% end   %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>果壳TODAY</title>
			<%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track' => true %>
			<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
			<%= csrf_meta_tags %>
		<!--[if lt IE 9]>
		<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
		</script>
		<![endif]-->
	</head>
	<body>

    <%= render 'layouts/header' %>

    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>

		
	</body>
</html>